export const GovernanceReasonCode = {
  ASSESSMENT_NOT_COMPLETE: "ASSESSMENT_NOT_COMPLETE",
  REQUIRED_EVIDENCE_MISSING: "REQUIRED_EVIDENCE_MISSING",
  REQUIRED_EVIDENCE_FAILED: "REQUIRED_EVIDENCE_FAILED",
  REQUIRED_EVIDENCE_ERROR: "REQUIRED_EVIDENCE_ERROR",
  REQUIRED_EVIDENCE_SKIPPED: "REQUIRED_EVIDENCE_SKIPPED",
  EVIDENCE_TRUST_INSUFFICIENT: "EVIDENCE_TRUST_INSUFFICIENT",
  SUBJECT_BINDING_MISMATCH: "SUBJECT_BINDING_MISMATCH",
  PROFILE_BINDING_MISMATCH: "PROFILE_BINDING_MISMATCH",
  POLICY_BINDING_MISMATCH: "POLICY_BINDING_MISMATCH",
  EXECUTION_CONTRACT_MISMATCH: "EXECUTION_CONTRACT_MISMATCH"
} as const;

export type GovernanceReasonCode =
  (typeof GovernanceReasonCode)[keyof typeof GovernanceReasonCode];

export function normalizeGovernanceReasonCodes(input: string[]): string[] {
  return Array.from(new Set(input)).sort((left, right) => left.localeCompare(right));
}
